/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-07-13 01:05:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import Modelos.Perfil;

public final class listadoPerfil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1>Listado de Perfiles</h1>\r\n");
      out.write("        <table>\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>Código</th>\r\n");
      out.write("                    <th>Nombre</th>\r\n");
      out.write("                    <th>Acciones</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                ");
 
                List<Perfil> listado = (List<Perfil>) request.getAttribute("listado");
                if (listado != null && !listado.isEmpty()) {
                    for (Perfil perfil : listado) {
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td class=\"text-center\">");
      out.print( perfil.getIdPerfil() );
      out.write("</td>\r\n");
      out.write("                    <td class=\"text-center\">");
      out.print( perfil.getNombre() );
      out.write("</td>\r\n");
      out.write("                    <td class=\"actions text-center\">\r\n");
      out.write("                        <a href=\"Perfil?accion=Modificar&idPerfil=");
      out.print( perfil.getIdPerfil() );
      out.write("\">Editar</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"Perfil?accion=Eliminar&idPerfil=");
      out.print( perfil.getIdPerfil() );
      out.write("\">Eliminar</a>\r\n");
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");
 
                    }
                } else {
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td class=\"text-center\" colspan=\"3\">No se encontraron perfiles.</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("        <br>\r\n");
      out.write("        <a href=\"registroPerfil.jsp\" style=\"text-decoration: none; display: block; text-align: center; padding: 10px; background-color: #4CAF50; color: white; border-radius: 4px;\">Registrar Nuevo Perfil</a>\r\n");
      out.write("    </div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
